- .github/workflows/sanity.yaml
- .golangci.yaml
- Makefile
- controllers/input_controller.go
- controllers/suite_test.go
- main.go
Update the Makefile and introduce the golangci-lint target to ensure
that local/CI environments use the same version of the golangci-lint
tool.
Update the sanity workflow and ensure CI is running the `lint` Makefile
target, which runs that golangci-lint target on the repository path.
Because we're replacing the golangci-lint github action with running a
Makefile target, we need to cache the go build/module paths so we don't
increase the overall CI sanity workflow time as that
action was previously handling that for us under-the-hood.
---
Update the root .golangci-lint configuration and enforce the
rukpakv1alpha1 and deppyv1alpha1 package import naming.
---
Fix any linting violations after updating that importas golangc-lint
configuration to enforce deppyv1alpha1 as the package import …
> ci: Add golangci-lint as a tool dependency

- Makefile
Add `export GOOS=linux` to the build-container target ala rukpak. 
Without this the deppy manager crash-loops if `make run` is run on macOS, since the binary build target is unspecified and inherited from the host OS.
> makefile: ensure build-container target produces linux binaries

- .github/workflows/stale.yaml
PRs will become stale after 30 days and will automatically be closed
30 days after being labeled as stale.
Issues will become stale after 60 days and maintainers can then close
the issue manually if appropriate.
Signed-off-by: Alexander Greene <greene.al1991@gmail.com>
> ci: Add GitHub Action to manage stale PRs/Issues

- internal/universe/entity_universe.go
- internal/universe/entity_universe_test.go
- internal/universe/search.go
- internal/universe/search_test.go
- internal/universe/universe_suite_test.go
The entity universe represents the complete set of entities over which deppy will operate. The entity universe surfaces methods for searching and sorting entities. The entity universe gives constraint factories the access to the entities in a queryable form, for instance:
```go
func packageDependency(subject solver.Identifier, packageName string, versionRange string) []solver.Constraint {
ids := entityUniverse.Search(universe.And(withPackageName(packageName), withinVersion(versionRange))).Sort(byChannelAndVersion).CollectIds()
return []solver.Constraint{solver.Dependency(subject, ids...)}
}
```
where `withPackageName`, `withinVersion`, `byChannelAndVersion` are `Predicate` and `SortFunction` implementations
> Add Entity universe

- internal/entitysource/cache_querier.go
- internal/entitysource/entity.go
- internal/entitysource/entity_source.go
- internal/entitysource/entity_test.go
- internal/entitysource/no_content.go
- internal/entitysource/query.go
- internal/entitysource/source_suite_test.go
This PR:
* adds entitysource package:
* exports Entity implementation
* exports EntitySource interface as a combination of two other interfaces: EntityQuerier and EntityContentGetter
* exports entitysource.Group a struct that aggregates multiple entity sources and gives the caller a singular interface for querying and content acquisition
* exports CacheQuerier an implementation of EntityQuerier in which all the data is in-memory
* exports NoContent an implementation of EntityContentGetter that returns no content
**Note**: I may have over engineered things here and separated the interfaces for querying and content acquisition
> Deppy Framework (2/7): EntitySource API

- cmd/dimacs/cmd.go
- cmd/dimacs/dimacs.go
- cmd/dimacs/dimacs_constraints.go
- cmd/dimacs/dimacs_source.go
- cmd/dimacs/dimacs_test.go
- cmd/dimacs/solve_suite_test.go
- cmd/root/root.go
- internal/sat/constraints.go
- internal/sat/constraints_test.go
- internal/sat/lit_mapping.go
- internal/sat/search.go
- internal/sat/solve.go
- internal/sat/solve_test.go
- internal/sat/variable.go
- internal/solver/solver.go
This PR adds a deppy command for solving arbitrary sat problems described in dimacs format
**Note**: to make dimacs work I had to change the definition of sat.Constraint to export the previously unexported methods (e.g. anchor, apply, etc.), so that I could define my own constraint type. I think we need to figure out a way to build these constraints with And, Or, Not top level constraints.
> Deppy Framework (6/7): dimacs deppy command

- cmd/dimacs/dimacs_source.go
- cmd/root/root.go
- cmd/sudoku/cmd.go
- cmd/sudoku/sudoku.go
- internal/entitysource/no_content.go
This PR adds the `sudoku` sub-command to deppy cli. It will spit out a solved sudoku board.
**Note**: sudoku seems to have a bug in it where some of the boards have gaps in them. I'm really not sure where this issue is coming from, especially since it was actually pretty easy to model the constraints using the available constraint definitions...
> Deppy Framework (7/7): sudoku deppy command

- .github/workflows/sanity.yaml
- .golangci.yaml
- Makefile
It looks like we already had the Makefile scaffoldings but golangci-lint wasn't being run in the CI pipeline. Adds the .golanci-lint.yaml configuration file, and leverages the existing "lint" and "verify" Makefile targets to be runs as GHA jobs.
> Bump the golangci-lint tool dependency to v1.49.0

- internal/solver/solve.go
- internal/solver/solve_test.go
- pkg/deppy/api.go
Moves the `NotSatisfiable` error out of the internal package. It's important to make this error usable by users, for instance, to improve the way resolution errors are communicated
Signed-off-by: perdasilva <perdasilva@redhat.com>
> move NotSatisfiable error definition out of internal

- cmd/dimacs/cmd.go
- cmd/sudoku/cmd.go
- pkg/deppy/solver/solver.go
- pkg/deppy/solver/solver_test.go
This PR refactors the `Solution` struct to be a little more helpful. It now returns returns the resolution error (if any), the selected variables, given a variable ID you can see whether it has been selected, and with an option, all variables used in the resolution can also be returned.
Signed-off-by: perdasilva <perdasilva@redhat.com>
> Refactor solver solution struct

- pkg/deppy/input/cache_entity_source.go
- pkg/deppy/input/entity_source.go
- pkg/deppy/input/entity_source_test.go
- pkg/ext/olm/constraints_test.go
The "Get" function of the entity source did not return an error and instead only a nil entity when its not found. This PR modifies the same, to make it return an error.
Reason:
The method could be implmented with a client that fetches bundle contents from the cluster. The error returned from the client needs to be propagated. Even if its from an offline key-value store, it could be upto the library users to ignore the returned error. 
More info: https://github.com/operator-framework/operator-controller/pull/141#discussion_r1163271945
> [EntitySource] Modify entity source interface

- cmd/dimacs/cmd.go
- cmd/sudoku/cmd.go
- pkg/deppy/solver/solver.go
- pkg/deppy/solver/solver_test.go
This PR removes return `error` from `NewDeppySolver` as It never returns one.
> Removes return `error` from `NewDeppySolver`

- .github/workflows/e2e.yaml
- .github/workflows/sanity.yaml
- .github/workflows/unit.yaml
This helps to simplify workflow yamls a bit since we don't need to explicity use cache for go steps: `actions/setup-go@v4` does that for us by default.
> Updates github actions

- .github/workflows/sanity.yaml
- Makefile
Similar change in rukpak: https://github.com/operator-framework/rukpak/pull/631
With this change linter will be reporting in github-actions format which will then be displayed in-line in the PR diff like this:
Github action run summary will also have this information.
> Improving linter reporting in github actions

- .golangci.yaml
- cmd/dimacs/dimacs_test.go
- pkg/deppy/input/entity_source_test.go
Linter which checks for common ginkgo issues like wrong error assertions (`Expect(err).To(BeNil())` instead of 
`Expect(err).NotTo(HaveOccurred())`), etc.
It also identifies `Expect` calls without a matcher.
See https://github.com/operator-framework/rukpak/pull/637 for examples where it was super useful.
> Adds `ginkgolinter`

- pkg/deppy/solver/solver.go
- pkg/deppy/solver/solver_test.go
> fix: solution.Error() returns untyped nil when SAT

- internal/solver/solve_test.go
- pkg/deppy/api.go
Use new line instead of comma as a separator.
Example from operator-controller as yaml:
```yaml
status:
conditions:
- lastTransitionTime: "2023-11-13T13:43:28Z"
message: |-
constraints not satisfiable:
argocd-operator package uniqueness permits at most 1 of operatorhubio-argocd-operator-argocd-operator.v0.6.0, operatorhubio-argocd-operator-argocd-operator.v0.4.0
installed package argocd-operator requires at least one of operatorhubio-argocd-operator-argocd-operator.v0.4.0
installed package argocd-operator is mandatory
required package argocd-operator requires at least one of operatorhubio-argocd-operator-argocd-operator.v0.6.0
required package argocd-operator is mandatory
observedGeneration: 2
reason: ResolutionFailed
status: "False"
type: Resolved
```
And as json:
```json
{
"status": { …
```
> ✨ Replace separator in `NotSatisfiable` error

- internal/solver/solve.go
There is an unnecessary call to `s.litMap.AnchorIdentifiers()`.
> ✨ Avoid extra call to `AnchorIdentifiers()`

- internal/solver/lit_mapping.go
- internal/solver/solve_test.go
> ✨ Ensure solver output is deterministic

- cmd/dimacs/cmd.go
- cmd/dimacs/dimacs_constraints.go
- cmd/dimacs/dimacs_test.go
- cmd/sudoku/cmd.go
- cmd/sudoku/sudoku.go
- internal/solver/bench_test.go
- internal/solver/solve.go
- internal/solver/solve_test.go
- pkg/deppy/input/simple_variable.go
- pkg/deppy/solver/solver.go
- pkg/deppy/solver/solver_test.go
Instead of a variable source make Deppy accept a slice of variables as an input.
Closes #153
> ⚠️ Remove variable sources and make Deppy accept a slice of variables instead

- pkg/deppy/constraint/constraint.go
We export fields from constraints instead
Closes #154
> Remove getter methods from constraints

- pkg/deppy/solver/solve.go
> Update the error to indicate unknown outcome
